package magiccollege.net;

public interface GameConstants {
	public static final int SERVER_PORT = 8000;
	public static final int DB_SERVER_PORT = 6000;
	public static final String SERVER_IP = "172.18.159.197";
//	public static final String DB_SERVER_IP = "198.71.90.118";
	public static final String DB_SERVER_IP = SERVER_IP;
	public static final short FLAG_SERVERMESSAGE_LOGON = 1;//µÇÂ¼
	public static final short FLAG_SERVERMESSAGE_LOGIN = FLAG_SERVERMESSAGE_LOGON + 1;//×¢²á
	public static final short FLAG_SERVERMESSAGE_QUERYNAME = FLAG_SERVERMESSAGE_LOGIN + 1;
	public static final short FLAG_SERVERMESSAGE_FIGHTREQUEST = FLAG_SERVERMESSAGE_QUERYNAME + 1;
	public static final short FLAG_SERVERMESSAGE_ACCEPTFIGHT = FLAG_SERVERMESSAGE_FIGHTREQUEST + 1;
	public static final short FLAG_SERVERMESSAGE_BEGINFIGHT = FLAG_SERVERMESSAGE_ACCEPTFIGHT + 1;
	public static final short FLAG_SERVERMESSAGE_GETCARD = FLAG_SERVERMESSAGE_BEGINFIGHT + 1;
	public static final short FLAG_SERVERMESSAGE_BEFORECALCULATE = FLAG_SERVERMESSAGE_GETCARD + 1;
	public static final short FLAG_SERVERMESSAGE_AFTERCALCULATE = FLAG_SERVERMESSAGE_BEFORECALCULATE + 1;
	public static final short FLAG_SERVERMESSAGE_BEGINATTACK = FLAG_SERVERMESSAGE_AFTERCALCULATE + 1;
	public static final short FLAG_SERVERMESSAGE_DOUBLE = FLAG_SERVERMESSAGE_BEGINATTACK + 1;
	public static final short FLAG_SERVERMESSAGE_AFTERATTACK = FLAG_SERVERMESSAGE_DOUBLE + 1;
	public static final short FLAG_SERVERMESSAGE_GAMEOVER = FLAG_SERVERMESSAGE_AFTERATTACK + 1;
	
	public static final short FLAG_CLIENTMESSAGE_LOGON = 1;//µÇÂ¼
	public static final short FLAG_CLIENTMESSAGE_LOGIN = FLAG_CLIENTMESSAGE_LOGON + 1;//×¢²á
	public static final short FLAG_CLIENTMESSAGE_QUERYNAME = FLAG_CLIENTMESSAGE_LOGIN + 1;
	public static final short FLAG_CLIENTMESSAGE_ACCEPTFIGHT = FLAG_CLIENTMESSAGE_QUERYNAME + 1;
	public static final short FLAG_CLIENTMESSAGE_BEGINFIGHT = FLAG_CLIENTMESSAGE_ACCEPTFIGHT + 1;
	public static final short FLAG_CLIENTMESSAGE_SELECTHAND = FLAG_CLIENTMESSAGE_BEGINFIGHT + 1;
	public static final short FLAG_CLIENTMESSAGE_BEFORECALCULATE = FLAG_CLIENTMESSAGE_SELECTHAND + 1;
	public static final short FLAG_CLIENTMESSAGE_AFTERCALCULATE = FLAG_CLIENTMESSAGE_BEFORECALCULATE + 1;
	public static final short FLAG_CLIENTMESSAGE_BEGINATTACK = FLAG_CLIENTMESSAGE_AFTERCALCULATE + 1;
	public static final short FLAG_CLIENTMESSAGE_DOUBLE = FLAG_CLIENTMESSAGE_BEGINATTACK + 1;
	public static final short FLAG_CLIENTMESSAGE_AFTERATTACK =  FLAG_CLIENTMESSAGE_DOUBLE + 1;
	public static final short FLAG_CLIENTMESSAGE_GAMEOVER = FLAG_CLIENTMESSAGE_AFTERATTACK + 1;
}
